# Generated by Django 5.2.3 on 2025-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_independent_doctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='clinics',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
